name: User Profile Tests

on:
  push:
    branches-ignore: [ master ]
    paths: 
      - apis/userprofile/**  
      - .github/workflows/userprofile*.yml
  pull_request:
    branches: [ master ]
    paths: 
      - apis/userprofile/**
      - .github/workflows/userprofile*.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/userprofile    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

    - uses: actions/github-script@v4
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ github.workflow }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ github.workflow }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
